// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay);
void LargeBtn_Animation(lv_obj_t * TargetObject, int delay);
void MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay);
void MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay);
void HideBtn_Animation(lv_obj_t * TargetObject, int delay);
void ShowBtn_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Home_Scr
void ui_Home_Scr_screen_init(void);
extern lv_obj_t * ui_Home_Scr;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_TempsText;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_car1;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_car2;
extern lv_obj_t * ui_red;
extern lv_obj_t * ui_yellow;
extern lv_obj_t * ui_green;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_153250542);    // assets/kekonja_1_-removebg-preview.png
LV_IMG_DECLARE(
    ui_img_338068273);    // assets/outline-side-view-car-icon-isolated-on-white-background-free-vector-removebg-preview.png
LV_IMG_DECLARE(ui_img_red_png);    // assets/RED.png
LV_IMG_DECLARE(ui_img_yellow_png);    // assets/YELLOW.png
LV_IMG_DECLARE(ui_img_green_png);    // assets/GREEN.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
