// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui
#include "ui.h"
#include "esp_log.h"
#include "driver/gpio.h"

extern int state;
extern int radio_state;

void home_to_park(lv_event_t * e)
{ESP_LOGI("on", "failed on\n");
	state = 1;
}

void park_to_home(lv_event_t * e)
{
	state = 0;
}


void radio_switch(lv_event_t * e)
{
	if(radio_state)
	{
		gpio_set_level(14,1);
	}
	else gpio_set_level(14,0);
	radio_state = 1 - radio_state;
}

