// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void home_to_park(lv_event_t * e);
void radio_switch(lv_event_t * e);
void park_to_home(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
