// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -94);
    lv_obj_set_y(ui_Button3, 86);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFDE8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "HOME");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_car2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_car2, &ui_img_338068273);
    lv_obj_set_width(ui_car2, LV_SIZE_CONTENT);   /// 289
    lv_obj_set_height(ui_car2, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_car2, -54);
    lv_obj_set_y(ui_car2, -4);
    lv_obj_set_align(ui_car2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_car2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_car2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_red = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_red, &ui_img_red_png);
    lv_obj_set_width(ui_red, LV_SIZE_CONTENT);   /// 88
    lv_obj_set_height(ui_red, LV_SIZE_CONTENT);    /// 230
    lv_obj_set_x(ui_red, 57);
    lv_obj_set_y(ui_red, 0);
    lv_obj_set_align(ui_red, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_red, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_red, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_red, 80);

    ui_yellow = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_yellow, &ui_img_yellow_png);
    lv_obj_set_width(ui_yellow, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_yellow, LV_SIZE_CONTENT);    /// 222
    lv_obj_set_x(ui_yellow, 87);
    lv_obj_set_y(ui_yellow, 0);
    lv_obj_set_align(ui_yellow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yellow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yellow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_yellow, 110);

    ui_green = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_green, &ui_img_green_png);
    lv_obj_set_width(ui_green, LV_SIZE_CONTENT);   /// 71
    lv_obj_set_height(ui_green, LV_SIZE_CONTENT);    /// 213
    lv_obj_set_x(ui_green, 120);
    lv_obj_set_y(ui_green, -3);
    lv_obj_set_align(ui_green, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_green, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_green, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_green, 140);

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -5);
    lv_obj_set_y(ui_Label1, -99);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Distance:");

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
